# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test Build

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v2
      
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'temurin'
        
      - run: ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name: DailyShop
          path: build/libs/*.jar
